### ISSUE TITLE
error while installing on ubuntu 

### ISSUE THREAD

**Issue by ali77gh** [pmzi/CodeShare#8]
os: ubuntu 18.04 (kde desktop)
node version : v11.14.0
npm version : 6.9.0

while runing:
~~~posh
 $ sudo npm install
~~~

error:
~~~posh
npm ERR! code ETARGET
npm ERR! notarget No matching version found for event-stream@3.3.6
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'CodeLive'
npm ERR! notarget 
~~~
and million lines of warning like:
~~~posh
npm WARN tar ENOENT: no such file or directory, open /home/ali/temp/CodeLive/node_modules/.staging/lodash-es-6c1ef47e/_castArrayLikeObject.js
~~~

**Comment by felippe-regazio** [comment]
I also had errors when installing on Ubuntu 18.04 LTS.
Heres how i solved:

$ sudo apt-get install -g npm
$ hash -d npm
$ rm -rf node_modules
$ rm -rf package-lock.json
$ npm install

or you can try to find an alternative version for the package with
$ npm list event-stream

**Comment by ali77gh** [comment]
thanks.
it solved by running:

```
$ rm -rf node_modules
$ rm -rf package-lock.json
$ npm install
```
